/*
 * dlopen_hook trigger: the v1 Flutter path.
 *
 * install() (run from guard.c's constructor, as early as the library loads)
 * patches libflutter.so's dlopen (required) and android_dlopen_ext
 * (best-effort) GOT slots to point at our hooks, and -- on the no-Java /
 * DT_NEEDED path -- installs the key baked into regions.h. The engine's init
 * thread later calls dlopen("libapp.so") through the patched slot; our hook
 * calls the real dlopen, then decrypts the snapshot regions in the returned
 * handle before Dart_Initialize reads them.
 */
#include "dlopen_hook.h"

#include <stdlib.h>
#include <string.h>

#include "got_hook.h"
#include "key.h"
#include "log.h"
#include "memops.h"
#include "region_table.h"
#include "regions.h" /* GENERATED by tools/encrypt_snapshot.py: k_regions[],
                      * k_regions_count, GUARD_HAVE_EMBEDDED_KEY, and (when
                      * embedded) k_embedded_key. Run the packer pipeline
                      * before building this target -- see README. */

/* Must match the real dlopen/android_dlopen_ext signatures exactly -- these
 * are installed directly into libflutter.so's GOT, so the calling convention
 * has to be identical. */
typedef void *(*guard_dlopen_fn)(const char *filename, int flags);
struct android_dlextinfo; /* opaque; we never touch its fields */
typedef void *(*guard_dlopen_ext_fn)(const char *filename, int flags,
                                     const struct android_dlextinfo *extinfo);

static guard_dlopen_fn g_real_dlopen = NULL;
static guard_dlopen_ext_fn g_real_dlopen_ext = NULL;

/* dlopen("libapp.so") happens exactly once per process under normal Flutter
 * engine startup, but AES-CTR decryption is its own inverse only when applied
 * exactly once per (key, nonce): running it a second time on already-decrypted
 * memory would XOR the plaintext with the same keystream again and silently
 * turn it back into ciphertext. Guard against any (unexpected) repeat
 * dlopen("libapp.so"). Bionic serializes dlopen internally (global loader
 * lock), so a plain flag is sufficient -- no separate mutex needed here. */
static int g_libapp_handled = 0;

static int looks_like_libapp(const char *filename) {
  return filename != NULL && strstr(filename, "libapp.so") != NULL;
}

static void *finish_handle(void *handle, const char *filename) {
  if (!handle || !looks_like_libapp(filename)) return handle;

  if (g_libapp_handled) {
    GUARD_LOGW("finish_handle: repeat dlopen('%s') observed, NOT re-decrypting (see g_libapp_handled comment)", filename);
    return handle;
  }
  g_libapp_handled = 1;

  if (!guard_key_is_set()) {
    /* Should be unreachable: install() runs from the constructor before the
     * GOT patch can be hit. Leave the region encrypted rather than guess with
     * a NULL key -- the engine will reject the bad snapshot loudly instead. */
    GUARD_LOGE("finish_handle: key not initialized, refusing to touch '%s'", filename);
    return handle;
  }

  const uint8_t *key = guard_key_get();
  GUARD_LOGI("finish_handle: intercepted dlopen('%s'), decrypting %zu region(s)", filename, k_regions_count);

  /* Data regions first, in place -- see guard_decrypt_data_region()'s comment
   * on why that's safe for these. */
  for (size_t i = 0; i < k_regions_count; i++) {
    if (k_regions[i].exec) continue;
    if (guard_decrypt_data_region(handle, &k_regions[i], key) != 0) {
      GUARD_LOGE("finish_handle: FATAL decrypting data region '%s', aborting process", k_regions[i].symbol);
      abort(); /* fail closed */
    }
  }

  /* Exec regions together, via the MAP_FIXED anon-replacement path -- see
   * guard_decrypt_exec_regions()'s comment for why these can't use the simple
   * in-place approach above. */
  if (guard_decrypt_exec_regions(handle, k_regions, k_regions_count, key) != 0) {
    GUARD_LOGE("finish_handle: FATAL decrypting exec region span, aborting process");
    abort(); /* fail closed */
  }

  return handle;
}

static void *my_dlopen(const char *filename, int flags) {
  void *h = g_real_dlopen ? g_real_dlopen(filename, flags) : NULL;
  return finish_handle(h, filename);
}

static void *my_dlopen_ext(const char *filename, int flags, const struct android_dlextinfo *extinfo) {
  void *h = g_real_dlopen_ext ? g_real_dlopen_ext(filename, flags, extinfo) : NULL;
  return finish_handle(h, filename);
}

/* No-Java / DT_NEEDED injection path: when the packer baked the key into
 * regions.h (--embed-key), install it here, in install() (which runs in the
 * constructor), so it is ready before the engine's dlopen("libapp.so") fires
 * -- there is no GuardBridge to call nativeSetKey() on this path. No-op on the
 * Java/Application path (nativeSetKey supplies the key instead). */
static void apply_embedded_key(void) {
#if GUARD_HAVE_EMBEDDED_KEY
  guard_key_set(k_embedded_key);
  GUARD_LOGI("dlopen_hook: embedded key installed (no-Java/DT_NEEDED path)");
#endif
}

static int dlopen_hook_install(void) {
  guard_generic_fn real_dlopen = NULL;
  guard_generic_fn real_dlopen_ext = NULL;

  if (guard_hook_got_symbol("libflutter.so", "dlopen", (void *)my_dlopen, &real_dlopen) != 0) {
    /* Without this hook, dlopen("libapp.so") returns the encrypted snapshot
     * untouched and Dart_Initialize fails deep inside the engine with a
     * confusing "wrong snapshot version" error. Fail fast and loud here. */
    GUARD_LOGE("dlopen_hook: FATAL, could not hook dlopen in libflutter.so");
    return -1;
  }

  /* Best-effort: our reference build's libflutter.so only imports plain dlopen
   * (verified against the sample APK), not android_dlopen_ext. Some engine/NDK
   * versions may differ, so we still try, but absence is expected. */
  if (guard_hook_got_symbol("libflutter.so", "android_dlopen_ext", (void *)my_dlopen_ext, &real_dlopen_ext) != 0) {
    GUARD_LOGI("dlopen_hook: android_dlopen_ext not imported by libflutter.so (expected on most builds), skipping");
    real_dlopen_ext = NULL;
  }

  g_real_dlopen = (guard_dlopen_fn)real_dlopen;
  g_real_dlopen_ext = real_dlopen_ext ? (guard_dlopen_ext_fn)real_dlopen_ext : NULL;

  /* Set the key before the hook can fire -- on the embedded path this closes
   * the hooked-but-no-key-yet window entirely. */
  apply_embedded_key();
  return 0;
}

const guard_trigger_t guard_trigger_dlopen_hook = {"dlopen_hook", dlopen_hook_install};
