#include "trampoline.h"

#include <dlfcn.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

#include "log.h"
#include "region_table.h"
#include "regions.h" /* GENERATED by tools/encrypt_snapshot.py; defines
                       * k_regions[] / k_regions_count for the ABI this TU is
                       * compiled for. Run the packer pipeline before
                       * building this target -- see README. */

static guard_dlopen_fn g_real_dlopen = NULL;
static guard_dlopen_ext_fn g_real_dlopen_ext = NULL;
static uint8_t g_key[GUARD_AES_KEY_LEN];
static int g_key_set = 0;

/* dlopen("libapp.so") happens exactly once per process under normal Flutter
 * engine startup, but AES-CTR decryption is its own inverse only when
 * applied exactly once per (key, nonce): running it a second time on
 * already-decrypted memory would XOR the plaintext with the same keystream
 * again and silently turn it back into ciphertext. Guard against any
 * (unexpected) repeat dlopen("libapp.so") call re-corrupting a live region.
 * Bionic serializes dlopen internally (global loader lock), so a plain flag
 * is sufficient -- no separate mutex needed here. */
static int g_libapp_handled = 0;

void guard_trampoline_init_hooks(guard_dlopen_fn real_dlopen, guard_dlopen_ext_fn real_dlopen_ext) {
  g_real_dlopen = real_dlopen;
  g_real_dlopen_ext = real_dlopen_ext;
}

void guard_trampoline_set_key(const uint8_t key[GUARD_AES_KEY_LEN]) {
  memcpy(g_key, key, GUARD_AES_KEY_LEN);
  g_key_set = 1;
}

/*
 * Decrypts one region in place. Returns 0 on success. On any failure
 * (missing symbol aside -- that's non-fatal, see below) returns -1 and the
 * caller aborts the process: v1 has no safe partial-failure recovery path.
 * A half-decrypted or still-encrypted-but-marked-executable region is worse
 * than a clean crash -- see README "W^X fallback (v1 vs v2)".
 */
static int decrypt_region(void *handle, const guard_region_t *region) {
  void *addr = dlsym(handle, region->symbol);
  if (!addr) {
    /* Per §7: skip if null. A region symbol can legitimately be absent
     * (e.g. stripped or optimized away in a future engine version); treat
     * that as nothing-to-do rather than fatal. */
    GUARD_LOGW("decrypt_region: dlsym('%s') returned NULL, skipping", region->symbol);
    return 0;
  }

  const size_t pagesize = (size_t)sysconf(_SC_PAGESIZE);
  const uintptr_t a = (uintptr_t)addr;
  const uintptr_t pg = a & ~(uintptr_t)(pagesize - 1);
  const uintptr_t region_end = a + region->size;
  const uintptr_t pg_end = (region_end + pagesize - 1) & ~(uintptr_t)(pagesize - 1);
  const size_t len = (size_t)(pg_end - pg);

  if (mprotect((void *)pg, len, PROT_READ | PROT_WRITE) != 0) {
    /* This is the W^X / SELinux execmod failure mode from §9.1. v1 does not
     * implement the anon-exec-mapping + engine-blob-mode fallback described
     * there (it requires replacing the app's FlutterActivity/engine
     * embedding to accept raw snapshot pointers, which is a separate,
     * unverified engineering effort -- see README "Known limitations (v1)").
     * Fail loudly instead of silently leaving ciphertext mapped executable. */
    GUARD_LOGE(
        "decrypt_region: mprotect(RW) failed for '%s' at %p (errno=%d) -- "
        "W^X fallback not implemented in v1, see README",
        region->symbol, addr, errno);
    return -1;
  }

  guard_aes_ctr_xcrypt(g_key, region->nonce, (uint8_t *)addr, region->size);

  const int target_prot = region->exec ? (PROT_READ | PROT_EXEC) : PROT_READ;
  if (mprotect((void *)pg, len, target_prot) != 0) {
    GUARD_LOGE(
        "decrypt_region: mprotect(%s) failed for '%s' after decrypt "
        "(errno=%d) -- plaintext left RW, aborting",
        region->exec ? "RX" : "R", region->symbol, errno);
    return -1;
  }

  if (region->exec) {
    __builtin___clear_cache((char *)pg, (char *)(pg + len)); /* mandatory on ARM64, see §9.2 */
  }

  GUARD_LOGI("decrypt_region: decrypted '%s' (%zu bytes) at %p", region->symbol, region->size, addr);
  return 0;
}

static int looks_like_libapp(const char *filename) {
  return filename != NULL && strstr(filename, "libapp.so") != NULL;
}

static void *finish_handle(void *handle, const char *filename) {
  if (!handle || !looks_like_libapp(filename)) return handle;

  if (g_libapp_handled) {
    GUARD_LOGW("finish_handle: repeat dlopen('%s') observed, NOT re-decrypting (see g_libapp_handled comment)", filename);
    return handle;
  }
  g_libapp_handled = 1;

  if (!g_key_set) {
    /* Should be unreachable: guard.c must call guard_trampoline_init() from
     * its constructor before the GOT patch can be hit. Leave the region
     * encrypted rather than guess -- the engine will reject the bad
     * snapshot magic/version loudly instead of us crashing on a NULL key. */
    GUARD_LOGE("finish_handle: key not initialized, refusing to touch '%s'", filename);
    return handle;
  }

  GUARD_LOGI("finish_handle: intercepted dlopen('%s'), decrypting %zu region(s)", filename, k_regions_count);
  for (size_t i = 0; i < k_regions_count; i++) {
    if (decrypt_region(handle, &k_regions[i]) != 0) {
      GUARD_LOGE("finish_handle: FATAL decrypting region %zu/%zu, aborting process", i + 1, k_regions_count);
      abort(); /* fail closed -- see decrypt_region() comment */
    }
  }
  return handle;
}

void *guard_my_dlopen(const char *filename, int flags) {
  void *h = g_real_dlopen ? g_real_dlopen(filename, flags) : NULL;
  return finish_handle(h, filename);
}

void *guard_my_dlopen_ext(const char *filename, int flags, const struct android_dlextinfo *extinfo) {
  void *h = g_real_dlopen_ext ? g_real_dlopen_ext(filename, flags, extinfo) : NULL;
  return finish_handle(h, filename);
}
